@REM set cc=zig cc -target i386-windows-gnu
@REM set cc=zig cc -target x86_64-windows-gnu
@REM set cc=gcc
set cc=tcc
set Includes=-Iinclude -Iexternal
@REM set Libraries=-lwinmm -lgdi32
set Libraries=
set ProjectName=emulator
set Code=src/main.c
set FullCode=%Code%
